"""add yookassa_payment_method_id field to payments table

Revision ID: 3b4070e5f9b5
Revises: c3b7afe7753e
Create Date: 2026-07-06 07:46:02.248443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b4070e5f9b5'
down_revision: Union[str, Sequence[str], None] = 'c3b7afe7753e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('yookassa_payment_method_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'yookassa_payment_method_id')
    # ### end Alembic commands ###
