"""add created_at column to user_category_follows and user_freelancer_profiles tables

Revision ID: 4374c7d23d8c
Revises: 58a2ff036a53
Create Date: 2026-06-27 01:30:09.979366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4374c7d23d8c'
down_revision: Union[str, Sequence[str], None] = '58a2ff036a53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_category_follows', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('user_freelancer_profiles', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_freelancer_profiles', 'created_at')
    op.drop_column('user_category_follows', 'created_at')
    # ### end Alembic commands ###
