"""add user_category_follows table

Revision ID: 56c6f3b9864a
Revises: 80386242a23b
Create Date: 2026-05-19 18:27:16.454482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56c6f3b9864a'
down_revision: Union[str, Sequence[str], None] = '80386242a23b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_category_follows',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['project_categories.id'], name=op.f('fk_user_category_follows_category_id_project_categories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_category_follows_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'category_id', name=op.f('pk_user_category_follows'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_category_follows')
    # ### end Alembic commands ###
