"""add user_generation_usage table

Revision ID: 5fc4c13ad605
Revises: bc7fe2665125
Create Date: 2026-07-13 05:39:53.525344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fc4c13ad605'
down_revision: Union[str, Sequence[str], None] = 'bc7fe2665125'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_generation_usage',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('free_generations', sa.Integer(), nullable=False),
    sa.Column('pro_generations', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_generation_usage_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user_generation_usage'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_generation_usage')
    # ### end Alembic commands ###
