"""add error column to payments table

Revision ID: 716acc5b57f6
Revises: 73c0543109a9
Create Date: 2026-07-09 06:35:31.282602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '716acc5b57f6'
down_revision: Union[str, Sequence[str], None] = '73c0543109a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('error', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'error')
    # ### end Alembic commands ###
