"""add projects table

Revision ID: cadc144bf404
Revises: 56c6f3b9864a
Create Date: 2026-05-20 17:32:54.749144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cadc144bf404'
down_revision: Union[str, Sequence[str], None] = '56c6f3b9864a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('possible_price_limit', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('offers', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['project_categories.id'], name=op.f('fk_projects_category_id_project_categories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects')),
    sa.UniqueConstraint('external_id', name=op.f('uq_projects_external_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects')
    # ### end Alembic commands ###
