services:
  postgres:
    image: postgres:18-trixie
    container_name: kworkflow_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql
  redis:
    image: redis:8.6.3-trixie
    container_name: kworkflow_redis
    env_file:
      - .env
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}

volumes:
  pgdata:
  redis_data: