services:
  telegram_bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    command: uv run telegram-bot
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    command: uv run taskiq worker kworkflow.main.worker:broker kworkflow.background_tasks.tasks --workers 1

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    command: uv run taskiq scheduler kworkflow.main.worker:scheduler kworkflow.background_tasks.tasks