"""add user_freelancer_profiles table

Revision ID: 02fe5f18888b
Revises: 052e8ef1194a
Create Date: 2026-05-22 14:21:10.585182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02fe5f18888b'
down_revision: Union[str, Sequence[str], None] = '052e8ef1194a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_freelancer_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('about', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_freelancer_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user_freelancer_profiles'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_freelancer_profiles')
    # ### end Alembic commands ###
