"""add updated_at column to payments table

Revision ID: 0907b7a498a7
Revises: e993b3df55a5
Create Date: 2026-07-07 07:34:59.505879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0907b7a498a7'
down_revision: Union[str, Sequence[str], None] = 'e993b3df55a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'updated_at')
    # ### end Alembic commands ###
