"""add user_roles table

Revision ID: 58a2ff036a53
Revises: ebadb3f5baca
Create Date: 2026-06-26 20:41:24.245247

"""
from kworkflow.users.models import Role
from datetime import datetime, UTC
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
from uuid import uuid7

# revision identifiers, used by Alembic.
revision: str = '58a2ff036a53'
down_revision: Union[str, Sequence[str], None] = 'ebadb3f5baca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_roles'))
    )
    # ### end Alembic commands ###
    conn = op.get_bind()
    user_ids = conn.execute(
        sa.text("SELECT id FROM users")
    ).scalars().all()

    if user_ids:
        now = datetime.now(tz=UTC)
        conn.execute(
            sa.insert(
                sa.table(
                    "user_roles",
                    sa.column("id", sa.UUID(as_uuid=True)),
                    sa.column("name", sa.String()),
                    sa.column("user_id", sa.UUID()),
                    sa.column("created_at", sa.DateTime(timezone=True)),
                    sa.column("updated_at", sa.DateTime(timezone=True))
                )
            ),
            [
                {
                    "id": uuid7(),
                    "name": Role.USER,
                    "user_id": user_id,
                    "created_at": now,
                    "updated_at": now,
                }
                for user_id in user_ids
            ]
        )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    # ### end Alembic commands ###
