"""add renewal_attempts column to subscriptions table

Revision ID: 73c0543109a9
Revises: 0907b7a498a7
Create Date: 2026-07-09 01:30:56.410459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73c0543109a9'
down_revision: Union[str, Sequence[str], None] = '0907b7a498a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('renewal_attempts', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'renewal_attempts')
    # ### end Alembic commands ###
