"""add is_active, update_at column to user_category_follows table

Revision ID: bc7fe2665125
Revises: 716acc5b57f6
Create Date: 2026-07-10 07:55:11.658144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc7fe2665125'
down_revision: Union[str, Sequence[str], None] = '716acc5b57f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_category_follows', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('user_category_follows', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_category_follows', 'updated_at')
    op.drop_column('user_category_follows', 'is_active')
    # ### end Alembic commands ###
