"""add user_stop_words table

Revision ID: bfb02fb387b6
Revises: 1afac6342bb9
Create Date: 2026-06-29 05:36:49.788040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfb02fb387b6'
down_revision: Union[str, Sequence[str], None] = '1afac6342bb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_stop_words',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('word', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_stop_words_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'word', name=op.f('pk_user_stop_words'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_stop_words')
    # ### end Alembic commands ###
