"""add subscribtion_plans, subscriptions, payments tables

Revision ID: d42916e51527
Revises: 4017c7c64977
Create Date: 2026-07-04 06:06:15.933143

"""
from kworkflow.subscriptions.models import PlanSlug
from datetime import datetime, UTC
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from uuid import uuid7

# revision identifiers, used by Alembic.
revision: str = 'd42916e51527'
down_revision: Union[str, Sequence[str], None] = '4017c7c64977'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('price_rub', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscription_plans')),
    sa.UniqueConstraint('slug', name=op.f('uq_subscription_plans_slug'))
    )
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('yookassa_payment_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_payments_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments')),
    sa.UniqueConstraint('yookassa_payment_id', name=op.f('uq_payments_yookassa_payment_id'))
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], name=op.f('fk_subscriptions_plan_id_subscription_plans'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_subscriptions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions'))
    )
    # ### end Alembic commands ###

    conn = op.get_bind()
    now = datetime.now(tz=UTC)
    conn.execute(
        sa.insert(
            sa.table('subscription_plans',
                sa.column('id', sa.UUID(as_uuid=True)),
                sa.column('name', sa.String()),
                sa.column('slug', sa.String()),
                sa.column('price_rub', sa.Numeric(10, 2)),
                sa.column('duration_days', sa.Integer()),
                sa.column('is_active', sa.Boolean()),
                sa.column('created_at', sa.DateTime(timezone=True)),
                sa.column('updated_at', sa.DateTime(timezone=True)),
            )
        ),
        [
            {
                "id": uuid7(), 
                "name": "PRO 3 Days", 
                "slug": PlanSlug.PRO_INITIAL,
                "price_rub": 1, 
                "duration_days": 3, 
                "is_active": True,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": uuid7(), 
                "name": "PRO Monthly", 
                "slug": PlanSlug.PRO_MONTHLY,
                "price_rub": 349, 
                "duration_days": 30, 
                "is_active": True, 
                "created_at": now, 
                "updated_at": now},
        ]
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscriptions')
    op.drop_table('payments')
    op.drop_table('subscription_plans')
    # ### end Alembic commands ###
