"""change duration_days column in subscription_plans table

Revision ID: db655b646a5e
Revises: 5fc4c13ad605
Create Date: 2026-07-14 06:55:47.629514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db655b646a5e'
down_revision: Union[str, Sequence[str], None] = '5fc4c13ad605'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscription_plans', 'duration_days',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscription_plans', 'duration_days',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
