"""add payment_id column to subscriptions table

Revision ID: e993b3df55a5
Revises: 3b4070e5f9b5
Create Date: 2026-07-07 07:16:16.731304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e993b3df55a5'
down_revision: Union[str, Sequence[str], None] = '3b4070e5f9b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('payment_id', sa.UUID(), nullable=False))
    op.create_unique_constraint(op.f('uq_subscriptions_payment_id'), 'subscriptions', ['payment_id'])
    op.create_foreign_key(op.f('fk_subscriptions_payment_id_payments'), 'subscriptions', 'payments', ['payment_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_subscriptions_payment_id_payments'), 'subscriptions', type_='foreignkey')
    op.drop_constraint(op.f('uq_subscriptions_payment_id'), 'subscriptions', type_='unique')
    op.drop_column('subscriptions', 'payment_id')
    # ### end Alembic commands ###
