"""add_prompt_and_api_metadata_to_project_proposals

Revision ID: ebadb3f5baca
Revises: 48ec5a5b6bf4
Create Date: 2026-06-22 02:10:57.057700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebadb3f5baca'
down_revision: Union[str, Sequence[str], None] = '48ec5a5b6bf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_proposals', sa.Column('prompt_tokens', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('project_proposals', sa.Column('completion_tokens', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('project_proposals', sa.Column('total_tokens', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('project_proposals', sa.Column('cost', sa.Numeric(precision=18, scale=10), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_proposals', 'cost')
    op.drop_column('project_proposals', 'total_tokens')
    op.drop_column('project_proposals', 'completion_tokens')
    op.drop_column('project_proposals', 'prompt_tokens')
    # ### end Alembic commands ###
