"""delete id column from project_proposals table

Revision ID: ffd44f4e09f0
Revises: bfb02fb387b6
Create Date: 2026-07-01 05:09:07.510726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffd44f4e09f0'
down_revision: Union[str, Sequence[str], None] = 'bfb02fb387b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_proposals', 'id')
    op.create_primary_key('pk_project_proposals', 'project_proposals', ['project_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pk_project_proposals', 'project_proposals', type_='primary')
    op.add_column('project_proposals', sa.Column('id', sa.UUID(), nullable=True))
    op.execute("UPDATE project_proposals SET id = gen_random_uuid()")
    op.alter_column('project_proposals', 'id', nullable=False)
    op.create_primary_key('pk_project_proposals', 'project_proposals', ['id'])
    # ### end Alembic commands ###
